### ISSUE TITLE
Blueprint Plugin No Longer Discovered

### ISSUE THREAD

**Issue by LordNex** [Tyrsis/BlueprintPlugin#51]
With this last patch when i boot up the server the Blueprint plugin is no longer listed. I double checked to make sure all the files were in their correct places and they are. Ive restarted it several times. Still no blueprint plugin listed in SESE. Any ideas?

**Comment by LordNex** [comment]
Confirmed, Ive tried to reload it, reinstall it, reboot it, everything. Cannot get the blueprint plugin to load under the current SESE. Anyone else having that issue?

**Comment by Tyrsis** [comment]
New version released, should fix this

**Comment by LordNex** [comment]
Yep looks good

Thank you
